# Generated by Django 3.0.7 on 2021-05-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtionaldetails',
            name='name',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
