# Generated by Django 3.0.7 on 2021-05-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20210518_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtionaldetails',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
