# Generated by Django 2.2 on 2021-06-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20210518_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtionaldetails',
            name='verified',
            field=models.IntegerField(default=0),
        ),
    ]
