# Generated by Django 2.2 on 2021-03-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtionaldetails',
            name='profile',
            field=models.CharField(default='', max_length=100),
        ),
    ]
