# Generated by Django 2.2 on 2021-05-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_addtionaldetails_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtionaldetails',
            name='rating',
        ),
        migrations.AddField(
            model_name='addtionaldetails',
            name='bio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addtionaldetails',
            name='designation',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
