# Generated by Django 2.2 on 2021-03-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_auto_20210303_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='profession',
        ),
        migrations.AddField(
            model_name='addtionaldetails',
            name='profession',
            field=models.CharField(default='user', max_length=10),
        ),
    ]
