# Generated by Django 2.2 on 2021-03-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_auto_20210303_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtionaldetails',
            name='profile',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
