# Generated by Django 2.2 on 2021-03-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_auto_20210303_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtionaldetails',
            name='profile',
            field=models.CharField(default='assets/images/avatar-1.png', max_length=100),
        ),
    ]
