# Generated by Django 2.2 on 2021-05-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_auto_20210303_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtionaldetails',
            name='profile',
            field=models.CharField(default='newassets/images/avatar-1.png', max_length=100),
        ),
    ]
