# Generated by Django 2.2 on 2021-01-29 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0002_auto_20210122_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 16, 8, 31, 214491)),
        ),
    ]
