# Generated by Django 2.2 on 2021-01-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0005_auto_20210129_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='rdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
