# Generated by Django 2.2 on 2021-01-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0007_auto_20210129_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='rdate',
            field=models.DateTimeField(null=True),
        ),
    ]
