# Generated by Django 2.2 on 2021-01-29 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0008_auto_20210129_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='adate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='rdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
