# Generated by Django 2.2 on 2021-02-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0009_auto_20210129_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddtionalDetails',
        ),
    ]
