# Generated by Django 2.2 on 2021-02-23 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0010_delete_addtionaldetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=254)),
                ('pharma', models.EmailField(max_length=254)),
                ('medicines', models.CharField(max_length=254)),
                ('rdate', models.DateField(default=datetime.date.today)),
                ('adate', models.DateTimeField(null=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
