# Generated by Django 2.2 on 2021-03-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0012_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='read',
            field=models.IntegerField(default=0),
        ),
    ]
