# Generated by Django 2.2 on 2021-05-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0014_record_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='medicines',
        ),
        migrations.AddField(
            model_name='orders',
            name='prescription',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
