# Generated by Django 2.2 on 2021-05-13 18:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0015_auto_20210513_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField(default=0)),
                ('mediname', models.CharField(max_length=254)),
                ('meditype', models.CharField(max_length=254)),
                ('quantity', models.IntegerField(default=0)),
                ('meal', models.CharField(max_length=254)),
                ('time', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
    ]
