# Generated by Django 2.2 on 2021-05-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0016_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='tid',
            field=models.IntegerField(default=0),
        ),
    ]
