# Generated by Django 2.2 on 2021-05-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0017_orders_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='bill',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
