# Generated by Django 2.2 on 2021-05-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0018_record_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='bill',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
