# Generated by Django 2.2 on 2021-05-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0019_orders_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='feedback',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
