# Generated by Django 2.2 on 2021-05-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0021_auto_20210518_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='feedback',
        ),
    ]
