# Generated by Django 2.2 on 2021-05-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0023_remove_record_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='feedst',
            field=models.IntegerField(default=0),
        ),
    ]
