# Generated by Django 2.2 on 2021-05-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0025_remove_record_feedst'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='feedst',
            field=models.IntegerField(default=0),
        ),
    ]
